### PR TITLE
Add unicode support.

### PR DESCRIPTION
**Pull request by macournoyer**
Add support for passing `u'...'` back to Ruby.

### CODE REVIEW

**Comment by halostatue** [comment]
Resolved with merge of Rupy into RubyPython.

**Comment by peter-wangxu** [comment]
Verified on my local. close it now.

**Comment by halostatue** [comment]
@peter-wangxu I’m not sure this actually got merged. The “Resolved with merge” *may* be a stray comment from an attempted issue import I performed (it looks like the expectation was that the issues would be blank, and all comments landed in the issue matching the bitbucket issue, not the created issue).

**Comment by peter-wangxu** [comment]
@halostatue I did some testing for the case @macournoyer mentioned, the `0.6.4` already contains the feature, so I thinkit's safe to close it for now.

**Pull request closed without merging**
